name: Sync and Update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_nodes]
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CLIENT_GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run update script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        URL: ${{ secrets.URL }}
        FLOW_ID: ${{ secrets.FLOW_ID }}
        NODE_ID: ${{ secrets.NODE_ID }}
      run: python node_updating.py