name: Sync New Python Files from NB36 to Taktile-Test

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Taktile-Test
        uses: actions/checkout@v2
        with:
          repository: Zachj345/Taktile-Test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: Taktile-Test

      - name: Checkout NB36-test
        uses: actions/checkout@v2
        with:
          repository: Zachj345/NB36-test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: NB36-test

      - name: Copy New Python Files
        run: |
          # Navigate to the NB36-test directory
          cd NB36-test

          # Find all Python files and copy them to the Taktile-Test directory
          for file in $(find . -name "*.py"); do
            # Copy only if the file does not exist in Taktile-Test or if it's newer
            if [ ! -f "../Taktile-Test/$file" ] || [ "$file" -nt "../Taktile-Test/$file" ]; then
              echo "Copying $file to Taktile-Test"
              mkdir -p "../Taktile-Test/$(dirname $file)"  # Create the directory if it doesn't exist
              cp "$file" "../Taktile-Test/$file"
            fi
          done

      - name: Commit and Push Changes
        run: |
          cd Taktile-Test
          git config user.name "github-actions"
          git config user.email "action@github.com"
          git add .
          git commit -m "Sync new Python files from NB36-test" || echo "No changes to commit"
          git remote add source https://github.com/Zachj345/Taktile-Test.git || echo "Remote 'source' already exists"
          git push source main
